# Use the base Codespace image
FROM mcr.microsoft.com/devcontainers/universal:2

# Install necessary packages
RUN apt-get update && apt-get install -y \
    tigervnc-standalone-server \
    novnc \
    websockify